lib/connectx: Fix build for prefixed architectures
We need to take into consideration the __USER_LABEL_PREFIX__
for architectures that define it when creating symbol aliases.

Fixes the build for the Meta(metag) architecture.

[...]
src/apps/sctp_test.c:801: undefined reference to `_sctp_connectx'
[...]

 [ Improved .symver handling to make it more readable, also x86_64
   objdump alias log attached below. -dborkman ]

Before:

$ objdump --syms ./src/lib/.libs/libsctp.so | grep @ | grep sctp
0000000000000df0 g     F .text	0000000000000032              sctp_connectx@
0000000000000e30 g     F .text	0000000000000029              sctp_connectx@VERS_2
0000000000000e60 g     F .text	0000000000000103              sctp_connectx@@VERS_3
0000000000000df0 g     F .text	0000000000000032              sctp_connectx@VERS_1

After:

$ objdump --syms ./src/lib/.libs/libsctp.so | grep @ | grep sctp
0000000000000df0 g     F .text	0000000000000032              sctp_connectx@
0000000000000e30 g     F .text	0000000000000029              sctp_connectx@VERS_2
0000000000000e60 g     F .text	0000000000000103              sctp_connectx@@VERS_3
0000000000000df0 g     F .text	0000000000000032              sctp_connectx@VERS_1

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Signed-off-by: Daniel Borkmann <dborkman@redhat.com>